import { AdminUser, AppUser, MasterCity, MasterDepartment, MasterDivision, MasterSource, MasterState, NewsItem, RoleItem } from './types';

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  { id: '1', srNo: 38, name: 'Rahul Mishra', email: 'rahul@gmail.com', phone: '', role: 'Content Analyst', status: 'Active' },
  { id: '2', srNo: 37, name: 'Sandeep', email: 'sandeep@gmail.com', phone: '', role: 'Dummy role', status: 'Active' },
  { id: '3', srNo: 35, name: 'Feroz', email: 'dgbtrdelan@gmail.com', phone: '00000000', role: 'Content Analyst', status: 'Active' },
  { id: '4', srNo: 34, name: 'Karan Bagga', email: 'karan.delhi@gmail.com', phone: '', role: 'Sub Admin', status: 'Active' },
  { id: '5', srNo: 32, name: 'Sunil Sharma', email: 'sunilsharma.hsn@gmail.com', phone: '7011029236', role: 'Sub Admin', status: 'Active' },
  { id: '6', srNo: 29, name: 'Rohit Kumar', email: 'sr.centarlanlystcchmrc@rpassm.in', phone: '', role: 'Content Analyst', status: 'Active' },
  { id: '7', srNo: 28, name: 'Alok Sarin', email: 'sr.centarlanlystcchmrc@rpassm.in', phone: '9416869136', role: 'Content Analyst', status: 'Active' },
  { id: '8', srNo: 27, name: 'Abhidey Thokral', email: 'sr.centarlanlystcchmrc@rpassm.in', phone: '', role: 'Admin Management', status: 'Active' },
  { id: '9', srNo: 26, name: 'Pooja', email: 'sandesh@gmail.com', phone: '', role: 'Content Analyst', status: 'Active' },
  { id: '10', srNo: 25, name: 'Virendra Kumar', email: 'vkumar.nr@gov.in', phone: '9876543210', role: 'Super Admin', status: 'Active' },
];

export const INITIAL_APP_USERS: AppUser[] = [
  { id: 'u1', srNo: 1, name: 'Ravi_Test', username: 'code.anantmishra@gmail.com', phone: '9888909898', status: 'Active' },
  { id: 'u2', srNo: 2, name: 'Rahul', username: 'rahul_ojan', phone: '9867011241', status: 'Active' },
  { id: 'u3', srNo: 3, name: 'Sandeep', username: 'Sandeep2', phone: '', status: 'Active' },
  { id: 'u4', srNo: 4, name: 'Abishey', username: 'abishey2', phone: '', status: 'Active' },
  { id: 'u5', srNo: 5, name: 'Mishra', username: 'jksandh999', phone: '8587054656', status: 'Active' },
  { id: 'u6', srNo: 6, name: 'Anand', username: 'anand99', phone: '9892223888', status: 'Active' },
  { id: 'u7', srNo: 7, name: 'Rohit', username: 'rail_news', phone: '', status: 'Active' },
  { id: 'u8', srNo: 8, name: 'Meenakshi', username: 'meenakshi_nr', phone: '', status: 'Active' },
  { id: 'u9', srNo: 9, name: 'Pooja', username: 'pooja_nr', phone: '', status: 'Active' },
  { id: 'u10', srNo: 10, name: 'Deepak Sharma', username: 'deepak.nr@gmail.com', phone: '9812345678', status: 'Active' },
];

export const INITIAL_ROLES: RoleItem[] = [
  { id: 'r1', srNo: 10, name: 'Dummy role', permissions: ['News Post'] },
  { id: 'r2', srNo: 9, name: 'Content Analyst', permissions: ['News Post', 'Report Management', 'Division Management', 'State Management', 'City/Village Management', 'Category Management', 'Source Management'] },
  { id: 'r3', srNo: 6, name: 'Data Analyst', permissions: ['News Post', 'Report Management', 'Division Management', 'State Management', 'City/Village Management', 'Category Management', 'Source Management'] },
  { id: 'r4', srNo: 4, name: 'Super Admin', permissions: ['Admin Management', 'User Management', 'News Post', 'Role Management', 'Report Management', 'Division Management', 'State Management', 'City/Village Management', 'Category Management', 'Source Management'] },
  { id: 'r5', srNo: 3, name: 'Sub Admin', permissions: ['News Post', 'Report Management', 'Division Management', 'State Management', 'City/Village Management', 'Category Management', 'Source Management'] },
  { id: 'r6', srNo: 2, name: 'User Management', permissions: ['User Management'] },
  { id: 'r7', srNo: 1, name: 'Admin Management', permissions: ['Admin Management', 'User Management', 'News Post', 'Role Management', 'Report Management', 'Division Management', 'State Management', 'City/Village Management', 'Category Management', 'Source Management'] },
];

export const INITIAL_DEPARTMENTS: MasterDepartment[] = [
  { id: 1, name: 'Medical', createdDate: '01-02-2026 09:28', updatedDate: '01-09-2026 09:28', subDepartments: ['Health Units', 'Hospital Administration', 'Sanitation'] },
  { id: 2, name: 'Security', createdDate: '01-02-2026 09:31', updatedDate: '01-09-2026 09:31', subDepartments: ['RPF Outposts', 'Crime Intelligence', 'Passenger Security'] },
  { id: 3, name: 'Signal & Telecom', createdDate: '01-02-2026 09:32', updatedDate: '01-09-2026 09:32', subDepartments: ['Automatic Signalling', 'Optical Fibre Comm', 'Kavach System'] },
  { id: 4, name: 'Electrical Department', createdDate: '01-02-2026 09:32', updatedDate: '01-09-2026 13:07', subDepartments: ['Traction Power', 'Station Electrification', 'Solar Plants'] },
  { id: 5, name: 'Mechanical', createdDate: '01-02-2026 09:32', updatedDate: '01-09-2026 09:32', subDepartments: ['Coaching Depot', 'Loco Shed', 'Wagon Care'] },
  { id: 6, name: 'Accounts', createdDate: '01-02-2026 09:33', updatedDate: '01-09-2026 09:33', subDepartments: ['Finance', 'Audit', 'Traffic Accounts'] },
  { id: 7, name: 'Commercial', createdDate: '01-02-2026 09:33', updatedDate: '01-09-2026 09:33', subDepartments: ['Freight Marketing', 'Ticket Checking', 'Passenger Amenities', 'Parcel Booking'] },
  { id: 8, name: 'Recruitment Info', createdDate: '01-02-2026 10:24', updatedDate: '01-09-2026 10:24', subDepartments: ['RRC Recruitment', 'Apprentice Training', 'Sports Quota'] },
  { id: 9, name: 'Construction Department', createdDate: '01-02-2026 12:54', updatedDate: '01-09-2026 13:38', subDepartments: ['New Lines', 'Doubling & Tripling', 'Bridge Engineering'] },
  { id: 10, name: 'General Administration', createdDate: '01-02-2026 09:30', updatedDate: '01-09-2026 09:30', subDepartments: ['Public Relations', 'Vigilance', 'General Management'] },
  { id: 11, name: 'Safety Department', createdDate: '01-02-2026 09:35', updatedDate: '01-09-2026 09:35', subDepartments: ['Accident Relief', 'Safety Audits', 'Track Inspections'] },
];

export const INITIAL_DIVISIONS: MasterDivision[] = [
  { id: 1, name: 'Moradabad', createdDate: '01-02-2026 06:03', updatedDate: '01-09-2026 06:03' },
  { id: 2, name: 'Ambala', createdDate: '01-02-2026 06:04', updatedDate: '01-09-2026 06:04' },
  { id: 3, name: 'Delhi', createdDate: '01-02-2026 06:04', updatedDate: '01-09-2026 06:04' },
  { id: 4, name: 'Ferozpur', createdDate: '01-02-2026 06:05', updatedDate: '01-09-2026 06:05' },
  { id: 5, name: 'Lucknow', createdDate: '01-02-2026 06:05', updatedDate: '01-09-2026 06:05' },
  { id: 6, name: 'Jammu', createdDate: '01-09-2026 14:56', updatedDate: '01-09-2026 14:56' },
];

export const INITIAL_SOURCES: MasterSource[] = [
  { id: 1, name: 'Print Media', createdDate: '01-02-2026 09:59', updatedDate: '01-09-2026 09:59', subSources: ['News Paper', 'Magazines', 'Weekly Journals', 'Gazette'] },
  { id: 2, name: 'Electronic Media', createdDate: '01-02-2026 09:59', updatedDate: '01-09-2026 09:59', subSources: ['TV News Channels', 'Radio / FM', 'Regional Broadcast'] },
  { id: 3, name: 'Social Media', createdDate: '01-02-2026 10:00', updatedDate: '01-09-2026 10:00', subSources: ['Twitter / X', 'Facebook', 'YouTube', 'Instagram', 'Koo'] },
];

export const INITIAL_STATES: MasterState[] = [
  { id: 1, name: 'Punjab', createdDate: '01-02-2026 06:29', updatedDate: '01-09-2026 06:29' },
  { id: 2, name: 'Haryana', createdDate: '01-02-2026 06:30', updatedDate: '01-09-2026 06:30' },
  { id: 3, name: 'Himachal Pradesh', createdDate: '01-02-2026 06:31', updatedDate: '01-09-2026 06:31' },
  { id: 4, name: 'Uttarakhand', createdDate: '01-02-2026 06:31', updatedDate: '01-09-2026 06:31' },
  { id: 5, name: 'Uttar Pradesh', createdDate: '01-02-2026 06:32', updatedDate: '01-09-2026 06:32' },
  { id: 6, name: 'Jammu and Kashmir', createdDate: '01-02-2026 06:32', updatedDate: '01-09-2026 06:32' },
  { id: 7, name: 'Delhi', createdDate: '01-02-2026 06:33', updatedDate: '01-09-2026 06:33' },
  { id: 8, name: 'Chandigarh', createdDate: '01-02-2026 06:34', updatedDate: '01-09-2026 06:34' },
];

export const INITIAL_CITIES: MasterCity[] = [
  { id: 1, name: 'Ghaziabad', pinCode: '201001', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:03', updatedDate: '01-09-2026 10:23' },
  { id: 2, name: 'Gautam Buddh Nagar', pinCode: '201301', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:24', updatedDate: '01-09-2026 10:24' },
  { id: 3, name: 'Meerut', pinCode: '250002', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:25', updatedDate: '01-09-2026 10:25' },
  { id: 4, name: 'Aligarh', pinCode: '202001', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:26', updatedDate: '01-09-2026 10:26' },
  { id: 5, name: 'Bareilly', pinCode: '243001', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:28', updatedDate: '01-09-2026 10:28' },
  { id: 6, name: 'Moradabad', pinCode: '244001', state: 'Uttar Pradesh', createdDate: '01-02-2026 10:34', updatedDate: '01-09-2026 10:34' },
  { id: 7, name: 'North West Delhi', pinCode: '110052', state: 'Delhi', createdDate: '01-02-2026 10:38', updatedDate: '01-09-2026 10:38' },
  { id: 8, name: 'North East Delhi', pinCode: '110053', state: 'Delhi', createdDate: '01-02-2026 10:40', updatedDate: '01-09-2026 10:40' },
  { id: 9, name: 'New Delhi', pinCode: '110001', state: 'Delhi', createdDate: '01-02-2026 10:42', updatedDate: '01-09-2026 10:42' },
  { id: 10, name: 'Ambala Cantt', pinCode: '133001', state: 'Haryana', createdDate: '01-02-2026 10:45', updatedDate: '01-09-2026 10:45' },
  { id: 11, name: 'Ferozepur City', pinCode: '152002', state: 'Punjab', createdDate: '01-02-2026 10:48', updatedDate: '01-09-2026 10:48' },
  { id: 12, name: 'Pathankot', pinCode: '145001', state: 'Punjab', createdDate: '01-02-2026 10:50', updatedDate: '01-09-2026 10:50' },
];

export const INITIAL_NEWS_ITEMS: NewsItem[] = [
  {
    id: 'news-1',
    srNo: 1,
    title: 'Amar Ujala - रेलवे माल गोदाम में बढ़ेगी बुनियादी सुविधाएं, सुधरेंगे प्लेटफार्म',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Moradabad',
    department: 'Commercial',
    subDepartment: 'Passenger Amenities',
    state: 'Uttar Pradesh',
    city: 'Hardoi',
    date: 'Sep 02, 2026',
    time: '12:13 pm',
    originUrl: 'https://amarujala.com/railway-news-hardoi-goods-shed',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `CITY - Hardoi - Amar Ujala - Page 4
रेलवे माल गोदाम में बढ़ेगी बुनियादी सुविधाएं, सुधरेंगे प्लेटफार्म
मजदूरों के बैठने के लिए प्लेटफार्म के शेड का होगा निर्माण, डीआरएम ने माल गोदाम का निरीक्षण कर दिए निर्देश।

हरदोई। उत्तर रेलवे मुरादाबाद मंडल के मंडल रेल प्रबंधक (डीआरएम) ने हरदोई रेलवे स्टेशन व माल गोदाम का गहन निरीक्षण किया। इस दौरान व्यापारियों व श्रमिकों की मांगों को ध्यान में रखते हुए माल गोदाम पर नए कवर्ड शेड, हाई-मास्ट लाइट, पेयजल सुविधा तथा प्लेटफार्म के फर्श की मरम्मत को तत्काल मंजूरी दी। डीआरएम ने अधिकारियों को निर्देश दिए कि सभी निर्माण कार्य आगामी तीन माह में गुणवत्ता के साथ पूर्ण किए जाएं ताकि माल ढुलाई और लोडिंग-अनलोडिंग में किसी भी प्रकार की असुविधा न हो।`,
    views: 1420,
    likes: 89,
  },
  {
    id: 'news-2',
    srNo: 2,
    title: 'Hindustan - डीआरएम ने किया स्टेशन व रोज़ा स्टेशन का किया निरीक्षण',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Moradabad',
    department: 'General Administration',
    subDepartment: 'General Management',
    state: 'Uttar Pradesh',
    city: 'Shahjahanpur',
    date: 'Sep 02, 2026',
    time: '12:06 pm',
    originUrl: 'https://livehindustan.com/uttar-pradesh/shahjahanpur/drm-inspection',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `CITY - Shahjahanpur - Hindustan - Page 4
डीआरएम ने किया स्टेशन व रोज़ा स्टेशन का किया निरीक्षण
अमृत भारत स्टेशन योजना के तहत चल रहे पुनर्विकास कार्यों का लिया जायजा।

शाहजहांपुर। मुरादाबाद रेल मंडल के डीआरएम ने बुधवार को शाहजहांपुर एवं रोज़ा जंक्शन का औचक निरीक्षण किया। उन्होंने अमृत भारत स्टेशन योजना के अंतर्गत बनाए जा रहे भव्य प्रवेश द्वार, नए फुट ओवर ब्रिज और आधुनिक प्रतीक्षालयों की प्रगति का अवलोकन किया। यात्री सुविधाओं में स्वच्छता, सुरक्षा एवं डिजिटल डिस्प्ले बोर्ड की स्थिति पर संतोष व्यक्त किया और कार्यदायी संस्था को तय समय सीमा के भीतर कार्य पूरा करने का आदेश दिया।`,
    views: 980,
    likes: 64,
  },
  {
    id: 'news-3',
    srNo: 3,
    title: 'Amrit Vichar - रोज़ा स्टेशन और कालोनी में पानी की समस्या हल होगी',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Moradabad',
    department: 'Commercial',
    subDepartment: 'Passenger Amenities',
    state: 'Uttar Pradesh',
    city: 'Shahjahanpur',
    date: 'Sep 02, 2026',
    time: '12:01 pm',
    originUrl: 'https://amritvichar.com/roza-station-water-supply-resolved',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `CITY - Shahjahanpur - Amrit Vichar - Page 5
रोज़ा स्टेशन और कालोनी में पानी की समस्या होगी दूर
रेलवे प्रशासन ने नए डीप ट्यूबवेल व संप हाउस निर्माण को दी हरी झंडी।

रोज़ा। रेलवे कालोनी व स्टेशन परिसर में ग्रीष्मकालीन पेयजल संकट से निपटने के लिए उत्तर रेलवे ने 50 लाख रुपये की लागत से अत्याधुनिक बोरवेल और डिस्ट्रीब्यूशन पाइपलाइन बिछाने की योजना को स्वीकृति दे दी है। रेल कर्मचारियों व स्थानीय निवासियों ने इस फैसले का स्वागत किया है।`,
    views: 750,
    likes: 42,
  },
  {
    id: 'news-4',
    srNo: 4,
    title: 'Amar Ujala - डीआरएम ने किया निरीक्षण',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Moradabad',
    department: 'General Administration',
    subDepartment: 'General Management',
    state: 'Uttar Pradesh',
    city: 'Moradabad',
    date: 'Sep 02, 2026',
    time: '11:52 am',
    originUrl: 'https://amarujala.com/moradabad-drm-inspections',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `मुरादाबाद। डीआरएम ने मंडल कार्यालय में सभी शाखा अधिकारियों के साथ उच्च स्तरीय संरक्षा बैठक की। संरक्षा मानकों के शत-प्रतिशत पालन और संरक्षा अभियान को गति देने के निर्देश दिए।`,
    views: 1120,
    likes: 78,
  },
  {
    id: 'news-5',
    srNo: 5,
    title: 'Dainik Jagran - लगातार स्वच्छता पखवाड़े की शुरुआत',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Moradabad',
    department: 'Commercial',
    subDepartment: 'Passenger Amenities',
    state: 'Uttar Pradesh',
    city: 'Moradabad',
    date: 'Sep 02, 2026',
    time: '11:47 am',
    originUrl: 'https://jagran.com/railway-cleanliness-pakhwada',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `CITY - Moradabad - Dainik Jagran - Page 7
लगातार स्वच्छता पखवाड़े की शुरुआत
स्टेशन परिसरों एवं ट्रेनों में 'स्वच्छ रेल, स्वच्छ भारत' अभियान के तहत विशेष सफाई अभियान शुरू किया गया। यात्रियों को सिंगल-यूज प्लास्टिक का प्रयोग न करने की शपथ दिलाई गई।`,
    views: 890,
    likes: 56,
  },
  {
    id: 'news-6',
    srNo: 6,
    title: 'The Tribune - Rly crossing reopens after 3 days',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ferozpur',
    department: 'Safety Department',
    subDepartment: 'Safety Audits',
    state: 'Punjab',
    city: 'Pathankot',
    date: 'Sep 01, 2026',
    time: '11:34 am',
    originUrl: 'https://tribuneindia.com/pathankot-railway-crossing-open',
    mediaType: 'Print Media',
    sentiment: 'Neutral',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `Pathankot: The level crossing near the outer yard which was closed for mandatory track maintenance and interlocking upgradation was successfully reopened for vehicular traffic on Wednesday morning. Commuters breathed a sigh of relief. Northern Railway engineers completed the track strengthening on record time.`,
    views: 640,
    likes: 31,
  },
  {
    id: 'news-7',
    srNo: 7,
    title: 'Dainik Jagran - अब नहीं होगी पैसेंजरों को कोई दिक्कत',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ferozpur',
    department: 'Operating',
    subDepartment: 'Train Operations',
    state: 'Punjab',
    city: 'Firozpur City',
    date: 'Sep 01, 2026',
    time: '11:30 am',
    originUrl: 'https://jagran.com/ferozpur-new-platforms-ready',
    mediaType: 'Print Media',
    sentiment: 'Neutral',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `फिरोजपुर। फिरोजपुर छावनी रेलवे स्टेशन पर नए सिग्नलिंग सिस्टम के चालू होने से अब गाड़ियों के समय पालन (पंचुअलिटी) में 15 प्रतिशत का सुधार दर्ज किया गया है।`,
    views: 520,
    likes: 29,
  },
  {
    id: 'news-8',
    srNo: 8,
    title: 'Dainik Savera - फिरोजपुर मंडल में लगातार टिकट जांच अभियान जारी',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ferozpur',
    department: 'Recruitment Info',
    subDepartment: 'Ticket Checking',
    state: 'Punjab',
    city: 'Pathankot',
    date: 'Sep 01, 2026',
    time: '11:00 am',
    originUrl: 'https://dainiksavera.com/ferozepur-ticket-checking-drive',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `Dainik Savera page no - 1 Pathankot
फिरोजपुर मंडल में लगातार टिकट जांच अभियान जारी
बिना टिकट यात्रा करने वालों पर शिकंजा कसा
पठानकोट। उत्तर रेलवे फिरोजपुर मंडल द्वारा चलाए जा रहे सघन टिकट चेकिंग अभियान के तहत पिछले माह में 1133 मामलों में 7 लाख 20 हजार रुपये से अधिक का जुर्माना वसूला गया। मंडल रेल प्रबंधक ने कहा कि उचित टिकट लेकर ही यात्रा करें।`,
    views: 1350,
    likes: 92,
  },
  {
    id: 'news-9',
    srNo: 9,
    title: 'Punjab Kesari - टिकट चेकिंग अभियान में करोड़ों की वसूली',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ferozpur',
    department: 'Commercial',
    subDepartment: 'Ticket Checking',
    state: 'Punjab',
    city: 'Sangrur',
    date: 'Aug 31, 2026',
    time: '10:56 am',
    originUrl: 'https://punjabkesari.in/sangrur-railway-record-fines',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `PUNJAB KESARI SANGRUR EDITION PAGE 2
रेलवे लाइन परियोजना पर केंद्र सरकार द्वारा 202.99 करोड़ रुपए खर्च किए जाएंगे : कैप्टन गुरजिंदर सिद्धू
संगरूर, पंजाब। रेल कनेक्टिविटी के विस्तार हेतु उत्तरी रेलवे ने संगरूर व आसपास के स्टेशनों पर आधुनिकीकरण कार्यों को वित्तीय स्वीकृति प्रदान की।`,
    views: 1890,
    likes: 120,
  },
  {
    id: 'news-10',
    srNo: 10,
    title: 'Dainik Bhaskar - 1155 यात्री बिना टिकट पकड़े गए',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ambala',
    department: 'Commercial',
    subDepartment: 'Ticket Checking',
    state: 'Haryana',
    city: 'Ambala Cantt',
    date: 'Aug 31, 2026',
    time: '10:45 am',
    originUrl: 'https://bhaskar.com/ambala-railway-fine-drive',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `अंबाला कैंट। वरिष्ठ मंडल वाणिज्य प्रबंधक के नेतृत्व में चलाए गए किलेबंदी टिकट जांच अभियान में विभिन्न सुपरफास्ट व एक्सप्रेस ट्रेनों में सघन जांच की गई। नियमों के उल्लंघन पर तुरंत चालान काटे गए।`,
    views: 1050,
    likes: 71,
  },
  {
    id: 'news-11',
    srNo: 11,
    title: 'Times of India - PM to flag off new Vande Bharat Express on Delhi-Amritsar route',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Delhi',
    department: 'Operating',
    subDepartment: 'Vande Bharat Operations',
    state: 'Delhi',
    city: 'New Delhi',
    date: 'Aug 30, 2026',
    time: '09:15 am',
    originUrl: 'https://timesofindia.com/vande-bharat-delhi-amritsar',
    mediaType: 'Print Media',
    sentiment: 'Positive',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `NEW DELHI: Northern Railway has completed trial runs of the semi-high-speed Vande Bharat rake between New Delhi and Amritsar via Ambala. The state-of-the-art train is equipped with Kavach automatic train protection, executive rotating chairs, panoramic windows, and regenerative braking.`,
    views: 3420,
    likes: 310,
  },
  {
    id: 'news-12',
    srNo: 12,
    title: 'Indian Express - Heavy monsoon rains delay train services on Kalka-Shimla hill railway',
    source: 'Print Media',
    subSource: 'News Paper',
    zone: 'Northern Zone',
    division: 'Ambala',
    department: 'Safety Department',
    subDepartment: 'Accident Relief',
    state: 'Himachal Pradesh',
    city: 'Ambala Cantt',
    date: 'Aug 29, 2026',
    time: '04:20 pm',
    originUrl: 'https://indianexpress.com/kalka-shimla-toy-train-rains',
    mediaType: 'Print Media',
    sentiment: 'Negative',
    roleName: 'Content Analyst',
    status: 'Published',
    accidentalNotification: false,
    description: `Shimla: Landslides triggered by incessant heavy rainfall led to temporary suspension of toy train services on the UNESCO World Heritage Kalka-Shimla railway section. Northern Railway emergency teams have been mobilized to clear debris near Solan.`,
    views: 1540,
    likes: 45,
  }
];
